language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4.0'
script: npm run travis
notifications:
  email:
    recipients:
      - redbugz+expressintl@gmail.com
    on_success: change
    on_failure: always
env:
  global:
    - secure: d6+fslWwEzmsV20LCxg5TR713xvTHWeKHyjmF8FMZ8JWnOf45Y4eX0LE1wUDfBJyJ4/RDkOYlY4qY/204uZW4rKWQ8MnJqV0V0KFhxJVugHuLNn+nV6H6jXWxiGZzyd5cXsFBjJzSsc0ORzu5hzo5NswHdX+baZKtlTNQLnKv92oGca5Pqys3d0/aww8Smr+Lqo2X5gfLk8AmsQgZZQBBF4LD0ON6iAfyKvOO6tqjE92RvQ8PyGW6+DFFzVQOsE1HZqPz/Aq9u2e5hYnAbVrBXmR1/xcy10e0FN+hmPkCpOwDbyJzV0UcCzwOolv6h4Yi5eFUtXgHI2KzdcsMmytCd6NoWROJXKw5R2D5I+xojxRyosAhI5r85WV3qHbWHhp/PGLP/0F+tGedDJwaiQ4m6widQXVRLBt+az/ru8Q9Wi4QTrTyjDPx4ai0RpLF43jB1QaC1kgf+rDAiFgLUWa8zfeIDJpj0oasb9L3I9k69ulVi27em+C8ki82bSO0ykiYtPHEn+acMjY6OWbY/qXch+PBXkSGL07BNM0p3QWO/kuqb8rxFIZFjIEAUbGnDFxB5N2gab0V3uzXDXwpu3aYC8M4ZeVmv+IRBHX3fzi5XvjeFuiQVo4RbeG3dGTDkQBsG+qB2IT32DCxKhUypKtLFqsVhVn4taIqNbCKfUAVLU=
    - secure: fMsi8IoVIalhdaVnNtT/aaDztwC2Fzd1RWdeSL82mNhz/XW2U0C34JxxbRRE81gZAR7Z17TSpkodZIXF2wzjgyICQsbnlRRKqnQhRfzCF6sbOXQPIwCM4CPgcDB8aIBdNzZX4y8WhlvGYKXgKOfzhcUmlpgH5jvxZI+mMcWsxEN42V4EqwOhLkN6G8khuNbPpAJOBM+VPGAWr3T1GwzSvRzOB0eydfUrRcllWflQPjqj3EGVwpOcQG8bieQ9nd5mLMP/QlrMQaNN+Web3flJor3H8EBiXuqpgLYL5AzkiDs4ITCfkFxiGVNuQME/R8wjagSzGZEF8zqRGIAIoEKHO+uT4Sg2syw5Qn7mg28b+yYOqGZOxGsQBEHvRoQQGVwc5zeCThVfNg1N2k83SVlXO84Z2BlUk7CEz/t0Af2am00EsimkQkYeAlFIzlpFBIDmgS85f45qr2qNkgoR8+dVr0DkJq2U7v395Q+XZ+JyvOW8Oq3Os5qn3AvVif6jPza+yF3zPRQsAV5eRrGhUbg401m2m1kM+FUOjXmEU0nYw5PJ3g1+x3XSYlEBboLkKwxZH2WXJD3SXBK49iHvCqirWoUtkuvdRu9sOyb0H8vbwIc/F7B25XY59GK8FeLIO8Y+5wgxH2IoMdtiSzLz5urjNE3F7L8PrBD308xglrnl8QM=
